# Generated by Django 2.2 on 2019-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
