# Generated by Django 2.2 on 2019-05-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_employee_emp_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sample_app.Company'),
        ),
    ]
